"""Query reformulation module: HyDE, Multi-query generation, and RRF fusion."""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass
from typing import Any, List, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Prompt Templates
# ---------------------------------------------------------------------------

_HYDE_PROMPT_FA = """<start_of_turn>user
شما یک متخصص سیستم اعتبارسنجی اعتباری ایران هستید. برای پرسش زیر، یک پاسخ کامل و دقیق بنویسید که حاوی اطلاعات کلیدی برای یافتن اسناد مرتبط باشد.

پرسش: {query}

پاسخ فرضی (شامل اصطلاحات کلیدی، مفاهیم تخصصی و جزئیات فنی):
<end_of_turn>
<start_of_turn>model
"""

_MULTI_QUERY_PROMPT_FA = """<start_of_turn>user
شما یک متخصص سیستم اعتبارسنجی اعتباری ایران هستید. برای پرسش زیر، {num_queries} صيغ مختلف پرسش تولید کنید که کاربر ممکن است بپرسد.

پرسش اصلی: {query}

انواع پرسش مورد نیاز:
1. Verbatim - بسیار نزدیک به متن اصلی
2. Paraphrase - با مترادف‌ها و تغییر ساختار
3. Conversational - محاوره‌ای (می‌شه، می‌تونم، یه سوال داشتم)
4. Typo - با اشتباهات تایپ واقعی (می‌شود→میشه، دسترسی→دسترسى)
4. Keyword-only - فقط اصطلاحات کلیدی تخصصی
5. Reworded - حذف کلمات + تغییر ترتیب سنگین

خروجی JSON (فقط آرایه JSON، بدون متن اضافه):
[
  "{{\"query\": \"...\", \"type\": \"verbatim\"}}",
  "{{\"query\": \"...\", \"type\": \"paraphrase\"}}",
  "{{\"query\": \"...\", \"type\": \"conversational\"}}",
  "{{\"query\": \"...\", \"type\": \"typo\"}}",
  "{{\"query\": \"...\", \"type\": \"keyword_only\"}}",
  "{{\"query\": \"...\", \"type\": \"reworded\"}}"
]
<end_of_turn>
<start_of_turn>model
"""


# ---------------------------------------------------------------------------
# Data Classes
# ---------------------------------------------------------------------------

@dataclass
class ReformulatedQuery:
    """A reformulated query with metadata."""
    query: str
    query_type: str
    original_query: str
    metadata: Optional[dict] = None


@dataclass
class HyDEDocument:
    """Hypothetical document generated by HyDE."""
    content: str
    query: str
    score: float = 0.0


# ---------------------------------------------------------------------------
# HyDE Generator
# ---------------------------------------------------------------------------

class HyDEGenerator:
    """Generates hypothetical documents (HyDE) for query expansion — DEPRECATED.

    Use ``kb_manager.hyde.HyDEGenerator`` (httpx + SentenceTransformer) as the
    canonical implementation. This class is kept for backward compat and now
    warns on instantiation (B13/B14 fix).
    """

    def __init__(
        self,
        llm_client: Any,
        prompt_template: str = _HYDE_PROMPT_FA,
        max_length: int = 512,
    ) -> None:
        import warnings

        warnings.warn(
            "kb_manager.query_reform.HyDEGenerator is deprecated; use kb_manager.hyde.HyDEGenerator",
            DeprecationWarning,
            stacklevel=2,
        )
        self._llm = llm_client
        self._prompt_template = prompt_template
        self._max_length = max_length
        self._cache: dict[str, HyDEDocument] = {}

    def generate(self, query: str) -> HyDEDocument:
        """Generate a hypothetical document for the query."""
        # Check cache
        cache_key = f"hyde:{query}"
        if cache_key in self._cache:
            return self._cache[cache_key]

        prompt = self._prompt_template.format(query=query)
        
        try:
            # Use the LLM client to generate hypothetical document
            response = self._llm.generate(
                prompt,
                max_tokens=self._max_length,
                temperature=0.3,
            )
            
            # Extract content from response
            content = self._extract_content(response)
            
            doc = HyDEDocument(content=content, query=query)
            self._cache[cache_key] = doc
            return doc
            
        except Exception as e:
            logger.warning("HyDE generation failed for query '%s': %s", query, e)
            # Return empty document on failure
            return HyDEDocument(content="", query=query)

    def _extract_content(self, response: Any) -> str:
        """Extract text content from LLM response."""
        if isinstance(response, str):
            return response.strip()
        if isinstance(response, dict):
            return response.get("text", "").strip()
        if hasattr(response, "text"):
            return response.text.strip()
        return str(response).strip()

    def embed_and_search(
        self,
        query: str,
        dense_index: Any,
        top_k: int = 10,
    ) -> List[tuple[str, float]]:
        """Generate HyDE doc, embed it, and search dense index (F7 fix: use correct API)."""
        hyde_doc = self.generate(query)
        if not hyde_doc.content:
            return []

        # DenseSemanticIndex.search expects string, not embedding; use content directly
        # (canonical HyDE uses embedding vector via dense._matrix @ hyde_vec in search.py)
        return dense_index.search(hyde_doc.content, top_k=top_k)


# ---------------------------------------------------------------------------
# Multi-Query Generator
# ---------------------------------------------------------------------------

class MultiQueryGenerator:
    """Generates multiple query reformulations for robust retrieval.

    Based on "A Surprisingly Simple yet Effective Multi-Query Rewriting Method
    for Conversational Passage Retrieval" (Kostric & Balog, 2024).
    Uses beam search to generate diverse reformulations.
    """

    def __init__(
        self,
        llm_client: Any,
        prompt_template: str = _MULTI_QUERY_PROMPT_FA,
        num_queries: int = 6,
        beam_size: int = 5,
    ) -> None:
        import warnings

        warnings.warn(
            "kb_manager.query_reform.MultiQueryGenerator is placeholder; use canonical retrieval or implement beam search",
            UserWarning,
            stacklevel=2,
        )
        self._llm = llm_client
        self._prompt_template = prompt_template
        self._num_queries = num_queries
        self._beam_size = beam_size
        self._cache: dict[str, List[ReformulatedQuery]] = {}

    def generate(self, query: str) -> List[ReformulatedQuery]:
        """Generate multiple reformulated queries."""
        cache_key = f"multi_query:{query}"
        if cache_key in self._cache:
            return self._cache[cache_key]

        prompt = self._prompt_template.format(
            query=query,
            num_queries=self._num_queries,
        )

        try:
            response = self._llm.generate(
                prompt,
                max_tokens=512,
                temperature=0.4,
            )
            
            content = self._extract_json(response)
            queries = self._parse_queries(content, query)
            
            self._cache[query] = queries
            return queries
            
        except Exception as e:
            logger.warning("Multi-query generation failed for '%s': %s", query, e)
            # Return at least the original query
            return [ReformulatedQuery(
                query=query,
                query_type="original",
                original_query=query,
            )]

    def _extract_json(self, response: Any) -> str:
        """Extract JSON from LLM response (F22 fix: strict, non-greedy)."""
        text = str(response).strip()
        # Try to parse first balanced JSON array via raw_decode
        try:
            start = text.find("[")
            if start != -1:
                decoder = json.JSONDecoder()
                obj, end = decoder.raw_decode(text[start:])
                return json.dumps(obj, ensure_ascii=False)
        except Exception:
            pass
        # Fallback: non-greedy regex
        match = re.search(r"\[.*?\]", text, re.DOTALL)
        if match:
            return match.group(0)
        return text

    def _parse_queries(self, json_text: str, original_query: str) -> List[ReformulatedQuery]:
        """Parse JSON array into ReformulatedQuery objects."""
        try:
            data = json.loads(json_text)
            queries = []
            for item in data:
                if isinstance(item, dict) and "query" in item:
                    queries.append(ReformulatedQuery(
                        query=item["query"],
                        query_type=item.get("type", "unknown"),
                        original_query=original_query,
                    ))
            return queries if queries else [
                ReformulatedQuery(query=original_query, query_type="original", original_query=original_query)
            ]
        except json.JSONDecodeError:
            return [ReformulatedQuery(query=original_query, query_type="original", original_query=original_query)]


# ---------------------------------------------------------------------------
# RRF Fusion
# ---------------------------------------------------------------------------

def reciprocal_rank_fusion(
    ranked_lists: List[List[tuple[str, float]]],
    k: int = 60,
    top_k: Optional[int] = None,
) -> List[tuple[str, float]]:
    """Reciprocal Rank Fusion (RRF) for combining multiple ranked lists.

    Args:
        ranked_lists: List of (doc_id, score) tuples, each list sorted by relevance.
        k: RRF constant (default 60).
        top_k: Optional limit on output size.

    Returns:
        List of (doc_id, fused_score) sorted by fused score descending.
    """
    fused_scores: dict[str, float] = {}
    
    for ranked_list in ranked_lists:
        for rank, (doc_id, _) in enumerate(ranked_list):
            rrf_score = 1.0 / (k + rank + 1)
            fused_scores[doc_id] = fused_scores.get(doc_id, 0) + rrf_score

    # Sort by fused score
    fused = sorted(fused_scores.items(), key=lambda x: x[1], reverse=True)
    
    if top_k:
        fused = fused[:top_k]
    
    return fused


def weighted_rrf(
    ranked_lists: List[List[tuple[str, float]]],
    weights: List[float],
    k: int = 60,
    top_k: Optional[int] = None,
) -> List[tuple[str, float]]:
    """Weighted Reciprocal Rank Fusion.

    Args:
        ranked_lists: List of ranked lists.
        weights: Weight for each list (should sum to 1.0).
        k: RRF constant.
        top_k: Optional limit.

    Returns:
        Fused ranked list.
    """
    if len(ranked_lists) != len(weights):
        raise ValueError("Number of ranked lists must match number of weights")

    fused_scores: dict[str, float] = {}
    
    for weight, ranked_list in zip(weights, ranked_lists):
        for rank, (doc_id, _) in enumerate(ranked_list):
            rrf_score = weight / (k + rank + 1)
            fused_scores[doc_id] = fused_scores.get(doc_id, 0) + rrf_score

    fused = sorted(fused_scores.items(), key=lambda x: x[1], reverse=True)
    
    if top_k:
        fused = fused[:top_k]
    
    return fused


# ---------------------------------------------------------------------------
# Query Type Detection
# ---------------------------------------------------------------------------

QUERY_TYPE_KEYWORDS = {
    "keyword_only": ["امتیاز", "اعتباری", "تسهیلات", "بازپرداخت", "ضامن", "گزارش", "اعتبارسنجی"],
    "conversational": ["می‌شه", "می‌تونم", "یه", "داشتم", "سلام", "ببخشید", "راستی"],
    "typo": ["میشه", "میکنن", "دسترسى", "اعتبارى", "قرارداد", "گزراش"],
    "reworded": ["نقش", "چیه", "چی", "تفاوت", "مراحل", "مرحله"],
}


def detect_query_type(query: str) -> str:
    """Heuristic detection of query type for adaptive retrieval."""
    query_lower = query.lower()
    
    scores = {}
    for qtype, keywords in QUERY_TYPE_KEYWORDS.items():
        score = sum(1 for kw in keywords if kw in query_lower)
        if score > 0:
            scores[qtype] = score
    
    if not scores:
        return "general"
    
    return max(scores, key=scores.get)


# ---------------------------------------------------------------------------
# Factory Functions
# ---------------------------------------------------------------------------

def create_hyde_generator(llm_client: Any) -> HyDEGenerator:
    """Create HyDE generator with default Persian prompt."""
    return HyDEGenerator(llm_client=llm_client)


def create_multi_query_generator(llm_client: Any) -> MultiQueryGenerator:
    """Create multi-query generator with default Persian prompt."""
    return MultiQueryGenerator(llm_client=llm_client)


def get_query_reform_components(llm_client: Any) -> tuple[HyDEGenerator, MultiQueryGenerator]:
    """Get both HyDE and multi-query generators."""
    return (
        HyDEGenerator(llm_client=llm_client),
        MultiQueryGenerator(llm_client=llm_client),
    )