# LLM-judge corpus — A_individual (12 failures)

## [1] IndividualCRMQuestions#59 (type A)
**QUERY:** من یه چک برگشتی داشتم، الان رفع سوءاثر شده. می‌خوام بدونم کی رتبه‌م درست می‌شه؟

**GOLD** [qa_pair]  (ranks bm25=45 dense=None merged=None final=None)
```
...‌شده را به صورت منظم بازپرداخت کند. کلیدواژه‌ها: ضمانت دیگران، افراد بدحساب، کاهش امتیاز اعتباری، دقت در ضمانت دسته‌بندی: تسهیلات، وام‌گیری و ضمانت مدل: حقیقی‌...
سوال: من یه چک برگشتی داشتم، الان رفع سوءاثر شده. می‌خوام بدونم کی رتبه‌م درست می‌شه؟
پاسخ کوتاه: بعد از ثبت رفع سوءاثر چک در بانک و اعمال آن در سامانه بانک مرکزی، ظرف ۲۴ ساعت این موضوع در گزارش اعتبارسنجی نمایش داده می‌شود. اما تأثیر چک برگشتی بر امتیاز اعتباری به‌تدریج و با گذشت زمان کم می‌شود، نه فوراً.
پاسخ کامل: پس از از اینکه بانک رفع سوءاثر چک‌ را ثبت کرد و در  سامانه بانک مرکزی اعمال گردید، ۲۴ ساعت بعد داخل گزارش اعتبارسنجی  اعمال می گردد و در صورتی که مشمول خط قرمز دیگری نباشید، امتیاز شما افزایش خواهد یافت.  توجه داشته باشید که در امتیاز اعتباری به مرور و با گذشت زمان، اثر چک برگشتی کاسته می‌شود.
کلیدواژه‌ها: رفع سوءاثر چک، سامانه بانک مرکزی، گزارش اعتبارسنجی، کاهش تدریجی تأثیر
دسته‌بندی: چک
مدل: حقیقی
```
**ACTUAL RETRIEVED WINNER** (stage=final_top5)
```
...‌و با گذشت زمان، اثر چک برگشتی کاسته می‌شود. کلیدواژه‌ها: رفع سوءاثر چک، سامانه بانک مرکزی، گزارش اعتبارسنجی، کاهش تدریجی تأثیر دسته‌بندی: چک مدل: حقیقی‌...
سوال: می‌خواستم بدونم اگه چک برگشتی داشته باشم، رتبه اعتباریم چی میشه؟
پاسخ کوتاه: با ثبت چک برگشتی در گزارش اعتباری شما، رتبه اعتباریتان در سامانه بانک مرکزی به پایین‌ترین سطح E3 (امتیاز 250) سقوط می‌کند و این وضعیت تا حدود ۲۴ ساعت پس از رفع سوءاثر ادامه دارد. بعد از رفع سوءاثر، رتبه و امتیاز اعتباری به‌تدریج بهبود می‌یابد.
پاسخ کامل: با توجه به اطلاعات آنلاین از سامانه چک‌های برگشتی بانک مرکزی، در صورت اعلام چک برگشتی، رتبه اعتباری شما به پایین‌ترین سطح یعنی E3 با امتیاز 250 کاهش پیدا می‌کند، تا زمانی که آن را رفع سو اثر کنید (حدود 24 ساعت بعد از رفع سو اثر). پس از رفع سو اثر، امتیاز شما افزایش پیدا می کند، اما وجود سابقه چک برگشتی رفع سو اثر شده تا ۵ سال در امتیاز  شما تاثیر منفی خواهد داشت.
کلیدواژه‌ها: چک برگشتی، رتبه اعتباری E3، رفع سوءاثر، بهبود تدریجی امتیاز
دسته‌بندی: چک
مدل: حقیقی
```
**Word stats:** query↔gold Jaccard=0.160 (shared 13: ['الان', 'بدونم', 'برگشتی', 'خوام', 'داشتم', 'درست', 'رتبه', 'رفع', 'سوءاثر', 'شه', 'چک', 'کی', 'یه']); query↔winner Jaccard=0.075 (shared 6: ['بدونم', 'برگشتی', 'رتبه', 'رفع', 'سوءاثر', 'چک']); gold_len=887 winner_len=961
**Gold content words absent from winner:** ['اعمال', 'افراد', 'الان', 'اینکه', 'بازپرداخت', 'باشید', 'بدحساب', 'تسهیلات', 'خط', 'خوام', 'داخل', 'داده', 'داشتم', 'درست', 'دقت', 'دیگران', 'دیگری', 'شه', 'صورتی', 'ضمانت', 'ظرف', 'فورا', 'قرمز', 'مرور', 'مشمول']

## [2] IndividualCRMQuestions#292 (type A)
**QUERY:** وام و اعتبار کدوم بانک ها و اپلیکیشن ها توی گزارش هست؟

**GOLD** [qa_pair]  (ranks bm25=None dense=None merged=None final=None)
```
...‌امتیاز اعتباری شما افزایش یابد و از رتبه E خارج شوید. کلیدواژه‌ها: رتبه قرمز، E3، صبر، بازپرداخت مناسب دسته‌بندی: امتیاز و رتبه اعتباری مدل: حقیقی‌...
سوال: وام و اعتبار کدوم بانک ها و اپلیکیشن ها توی گزارش هست؟
پاسخ کوتاه: برای مشاهده لیست تامین کنندگان اطلاعات به https://ics24.ir/about/creditors مراجعه کنید.
پاسخ کامل: برای مشاهده لیست تامین کنندگان اطلاعات به https://ics24.ir/about/creditors مراجعه کنید.
کلیدواژه‌ها: لیست تامین کننده اطلاعات، BNPL، لندتک
دسته‌بندی: دریافت گزارش و خدمات
مدل: حقیقی
```
**ACTUAL RETRIEVED WINNER** (stage=final_top5)
```
...‌اپلیکیشن موبایل شرکت با خدمات نوین و متنوع در دست اقدام قرار دارد. کلیدواژه‌ها: اعتباریتو، اپلیکیشن، گزارش اعتباری دسته‌بندی: دریافت گزارش و خدمات مدل: حقوقی‌...
سوال: حداقل امتیاز اعتباری مورد نیاز برای دریافت وام بانکی چقدر است؟
پاسخ کوتاه: تعیین حداقل امتیاز برای اعطای وام بر عهده بانک‌ها و لندتک‌هاست.
پاسخ کامل: شرکت اعتبارسنجی تنها ارائه‌دهنده امتیاز و رتبه اعتباری اشخاص حقیقی و حقوقی می‌باشد. لذا هرگونه تصمیم گیری در خصوص اعطای تسهیلات مطابق با سیاست های اعتباردهندگان می باشد و قاعدتا معیارها و شرایط لازم برای هر نوع از تسهیلات و برای هر گروه از امتیاز متفاوت خواهد بود.
کلیدواژه‌ها: امتیاز اعتباری، وام، بانک، اعطای تسهیلات
دسته‌بندی: امتیاز و رتبه اعتباری
مدل: حقوقی
```
**Word stats:** query↔gold Jaccard=0.140 (shared 6: ['اعتبار', 'اپلیکیشن', 'بانک', 'وام', 'کدوم', 'گزارش']); query↔winner Jaccard=0.065 (shared 4: ['اپلیکیشن', 'بانک', 'وام', 'گزارش']); gold_len=508 winner_len=684
**Gold content words absent from winner:** ['BNPL', 'E3', 'about', 'creditors', 'https', 'ics24', 'ir', 'اطلاعات', 'اعتبار', 'افزایش', 'بازپرداخت', 'تامین', 'خارج', 'شوید', 'صبر', 'قرمز', 'لیست', 'مراجعه', 'مشاهده', 'مناسب', 'کدوم', 'کننده', 'کنندگان', 'یابد']

## [3] IndividualCRMQuestions#315 (type A)
**QUERY:** رتبه من C شده و من تا حالا هیچ وامی نگرفتم،‌ چطور ممکنه؟

**GOLD** [qa_pair]  (ranks bm25=None dense=None merged=None final=None)
```
...‌مشاهده نمونه گزارش اعتباری، به وبسایت شرکت اعتبارسنجی ایران به نشانی www.ics24.ir مراجعه کنید. کلیدواژه‌ها: نمونه گزارش، ظاهر دسته‌بندی: دریافت گزارش و خدمات مدل: حقیقی‌...
سوال: رتبه من C شده و من تا حالا هیچ وامی نگرفتم،‌ چطور ممکنه؟
پاسخ کوتاه: رتبه اعتباری و امتیاز اعتباری شما بر اساس اطلاعات جایگزین محاسبه شده است.
پاسخ کامل: رتبه اعتباری و امتیاز اعتباری شما بر اساس اطلاعات جایگزین محاسبه شده است.
کلیدواژه‌ها: اطلاعات جایگزین، بدون وام
دسته‌بندی: امتیاز و رتبه اعتباری
مدل: حقیقی
```
**ACTUAL RETRIEVED WINNER** (stage=final_top5)
```
...‌رتبه پایین‌تر (مثلاً C1) بهتر است؛ چراکه اختلاف بین رتبه‌های اصلی (B و C) از اختلاف بین زیررده‌ها مهم‌تر است. کلیدواژه‌ها: رتبه اصلی، زیر رده‌...
سوال: امتیازم تغییر کرده ولی رتبم تغییر نکرده. چطور ممکنه؟
پاسخ کوتاه: هر رتبه محدوده ای از امتیاز را شامل می شود.
پاسخ کامل: هر رتبه محدوده ای از امتیاز را شامل می شود و ممکن است امتیاز شما تغییر کند، ولی در همان محدوده امتیازی رتبه فعلی خود بمانید.
کلیدواژه‌ها: امتیاز تغییر، رتبه بدون تغییر
```
**Word stats:** query↔gold Jaccard=0.179 (shared 7: ['حالا', 'رتبه', 'ممکنه', 'نگرفتم', 'هیچ', 'وامی', 'چطور']); query↔winner Jaccard=0.071 (shared 3: ['رتبه', 'ممکنه', 'چطور']); gold_len=493 winner_len=443
**Gold content words absent from winner:** ['ics24', 'ir', 'www', 'اساس', 'اطلاعات', 'اعتبارسنجی', 'اعتباری', 'ایران', 'بندی', 'جایگزین', 'حالا', 'حقیقی', 'خدمات', 'دریافت', 'دسته', 'شرکت', 'ظاهر', 'محاسبه', 'مدل', 'مراجعه', 'مشاهده', 'نشانی', 'نمونه', 'نگرفتم', 'هیچ']

## [4] IndividualCRMQuestions#340 (type A)
**QUERY:** کدوم دلایل برگشت چک توی امتیاز مهمه؟

**GOLD** [qa_pair]  (ranks bm25=None dense=None merged=None final=None)
```
...‌در امتیاز اعتباری افراد تاثیرگذار است. کلیدواژه‌ها: وزن سابقه بازپرداخت، سهم مالیات، سهم چک، سابقه کافی یک سال دسته‌بندی: عوامل موثر بر امتیاز مدل: حقیقی‌...
سوال: کدوم دلایل برگشت چک توی امتیاز مهمه؟
پاسخ کوتاه: چک‌هایی که به دلیل «فقدان موجودی»، «کمبود موجودی» یا «مسدودی حساب» برگشت خورده باشند، در محاسبه امتیاز اعتباری شما مؤثر هستند.
پاسخ کامل: چک‌هایی که به دلیل «فقدان موجودی»، «کسری موجودی» یا «مسدودی حساب» برگشت خورده باشند، در کاهش امتیاز اعتباری شما مؤثرند. در نظر داشته باشید با رفع سوءاثر به‌موقع این چک‌ها می‌توانید از تأثیر منفی بیشتر آن‌ها بر امتیاز اعتباری جلوگیری کنید.
کلیدواژه‌ها: فقدان موجودی، کمبود موجودی، مسدودی حساب، رفع سوءاثر به‌موقع
دسته‌بندی: چک
مدل: حقیقی
```
**ACTUAL RETRIEVED WINNER** (stage=final_top5)
```
...‌کلیدواژه‌ها: تعداد، چک برگشتی، 2 سال اخیر کد دلیل: -‌...
کلیدواژه‌ها: برگشت خوردن,تعداد چک,چک برگشتی
کد دلیل: ACH6-6
متن دلیل: فرد در 3 سال گذشته تعداد بسیار زیادی چک برگشتی داشته است.
توضیح کوتاه: سابقه چک برگشتی مهمترین عامل بر امتیاز چک شخص است. هر چه شخص تعداد چکهای برگشتی بیشتر و با مبالغ بیشتر داشته باشد، امتیاز چک وی کاهش بیشتری دارد.
توضیح کامل: سابقه چک برگشتی مهمترین عامل بر امتیاز چک شخص است. هر چه شخص تعداد چکهای برگشتی بیشتر و با مبالغ بیشتر داشته باشد، امتیاز چک وی کاهش بیشتری دارد. همچنین به صورت کلی هر چه چک در تاریخ نزدیکتری برگشت خورده باشد، تاثیر بیشتری بر امتیاز دارد و گذشت زمان به تدریج امتیاز را افزایش خواهد داد. به این ترتیب اگر چنین جمله ای در گزارش اعتبارسنجی چک درج شود به معنی وجود تعداد بسیار زیادی چک برگشتی در سابقه سه سال اخیر شخص است.
پیشنهاد بهبود: تنها راه برای از بین بردن تاثیر این رفتار در امتیاز، صبوری کردن است تا به تدریج امتیاز افزایش یابد.
```
**Word stats:** query↔gold Jaccard=0.113 (shared 6: ['امتیاز', 'برگشت', 'دلایل', 'مهمه', 'چک', 'کدوم']); query↔winner Jaccard=0.043 (shared 3: ['امتیاز', 'برگشت', 'چک']); gold_len=691 winner_len=893
**Gold content words absent from winner:** ['اعتباری', 'افراد', 'بازپرداخت', 'باشند', 'باشید', 'بندی', 'تأثیر', 'تاثیرگذار', 'توانید', 'جلوگیری', 'حساب', 'حقیقی', 'دسته', 'دلایل', 'رفع', 'سهم', 'سوءاثر', 'سوال', 'عوامل', 'فقدان', 'مؤثر', 'مؤثرند', 'مالیات', 'محاسبه', 'مدل']

## [5] IndividualCRMQuestions#347 (type A)
**QUERY:** من هیچ وامی نگرفته‌ام، ولی برای یک آشنا ضامن شده‌ام. آیا این روی امتیازم اثر دارد؟

**GOLD** [qa_pair]  (ranks bm25=None dense=None merged=None final=None)
```
...‌هرچند رو‌به‌کاهش، همچنان در گزارش باقی است. کلیدواژه‌ها: عوامل مؤثر بر امتیاز، تأخیر ضامن، حجم بالای تسهیلات جاری دسته‌بندی: امتیاز و رتبه اعتباری مدل: حقیقی‌...
سوال: من هیچ وامی نگرفته‌ام، ولی برای یک آشنا ضامن شده‌ام. آیا این روی امتیازم اثر دارد؟
پاسخ کوتاه: بله، تعداد و کیفیت ضمانت‌هایی که برای دیگران انجام داده‌اید، در امتیاز شما مؤثر است.
پاسخ کامل: ضمانت از دیگران، یکی از شاخص‌های مهم در اعتبارسنجی محسوب می‌شود؛ به‌ویژه برای افرادی که سابقه مستقیم دریافت تسهیلات ندارند. تعداد ضمانت‌هایی که انجام داده‌اید، و مهم‌تر از آن، اینکه فرد تحت ضمانت شما اقساط را به‌موقع پرداخت کرده یا خیر، بر امتیاز اعتباری‌تان تأثیر می‌گذارد. تأخیر متقاضی اصلی در بازپرداخت، می‌تواند امتیاز شما را نیز کاهش دهد.
کلیدواژه‌ها: ضمانت، مدل حقیقی جایگزین، تأخیر متقاضی اصلی
دسته‌بندی: تسهیلات، وام‌گیری و ضمانت
مدل: حقیقی
```
**ACTUAL RETRIEVED WINNER** (stage=final_top5)
```
...‌البته لازم به ذکر است که تسهیلات ضمانت شده تاثیر زیادی بر امتیاز شخص ندارد و سوابق فردی در حوزه چک اهمیت خیلی بیشتری دارند.‌...
کلیدواژه‌ها: ضامن,تسهیلات، بدهی سررسید شده
کد دلیل: DCB4-2
متن دلیل: تسهیلات ضمانت شده توسط فرد در یک سال گذشته، دارای مبلغ سررسید شده پرداخت نشده نسبتا زیاد بوده است.
توضیح کوتاه: بصورت کلی ضامن شدن در تسهیلاتی که وام‌گیرنده بدحسابی می‌کند، تا حدی امتیاز چک شخص ضامن را کاهش می‌دهد.
توضیح کامل: بصورت کلی ضامن شدن در تسهیلاتی که وام‌گیرنده بدحسابی می‌کند، تا حدی امتیاز چک شخص ضامن را کاهش می دهد. به همین خاطر باید شخص در ضمانت تسهیلات مراقبت بیشتری نموده و ضامن اشخاص بدحساب نشود. لازم به ذکر است که میزان تاثیر این رفتار بر ریسک برگشت چک با تحلیل آماری داده های واقعی و براساس نتیجه مدل هوش مصنوعی به دست آمده است.
پیشنهاد بهبود: در صورت وقوع چنین اتفاقی، پس از تسریع در پرداخت بدهی توسط بدهکار، شخص ضامن نیز باید  مدتی را صبرکند تا تاثیر این بدحسابی بر امتیازش از بین برود. البته لازم به ذکر است که تسهیلات ضمانت شده تاثیر زیادی بر امتیاز شخص ندارد و  سوابق فردی در حوزه چک اهمیت خیلی بیشتری دارند.
```
**Word stats:** query↔gold Jaccard=0.132 (shared 10: ['آشنا', 'اثر', 'ام', 'امتیازم', 'روی', 'ضامن', 'نگرفته', 'هیچ', 'وامی', 'ولی']); query↔winner Jaccard=0.011 (shared 1: ['ضامن']); gold_len=811 winner_len=1035
**Gold content words absent from winner:** ['آشنا', 'اثر', 'اصلی', 'اعتبارسنجی', 'اعتباری', 'افرادی', 'اقساط', 'ام', 'امتیازم', 'انجام', 'اید', 'اینکه', 'بازپرداخت', 'باقی', 'بالای', 'بله', 'بندی', 'تأثیر', 'تأخیر', 'تان', 'تحت', 'تر', 'تعداد', 'تواند', 'جاری']

## [6] IndividualCRMQuestions#352 (type A)
**QUERY:** بدهیمو پرداخت کردم.بعدش چی کار کنم؟

**GOLD** [qa_pair]  (ranks bm25=None dense=None merged=None final=None)
```
...‌است دریافت گزارش توسط خودِ شخص، در این شاخص محاسبه نمی‌شود. کلیدواژه‌ها: استعلام مکرر، بدون سابقه، کاهش امتیاز دسته‌بندی: عوامل موثر بر امتیاز مدل: حقیقی‌...
سوال: بدهیمو پرداخت کردم.بعدش چی کار کنم؟
پاسخ کوتاه: لازم است تا زمان به روزرسانی بعدی اطلاعات منتظر بمانید.
پاسخ کامل: لازم است تا زمان به روزرسانی بعدی اطلاعات منتظر بمانید. لازم به ذکر است که داده های تسهیلاتی به صورت ماهانه به روزرسانی می شود و دیگر اطلاعات حداکثر پس از ۲۴ ساعت به روز می شود. (در صورتی که امتیاز شما به علت وضعیت منفی معوق، وضعیت منفی مشکوک الوصول یا بیش از ۹۰ روز تاخیر متوالی در بازپرداخت ۲۵۰ شده باشد، ۲ ماه طول می کشد تا امتیاز شما پس از پرداخت اقساط سررسید شده از ۲۵۰ خارج شود.
کلیدواژه‌ها: ماهانه، اطلاعات تسهیلات
دسته‌بندی: اصلاح و به‌روزرسانی اطلاعات
مدل: حقیقی
```
**ACTUAL RETRIEVED WINNER** (stage=final_top5)
```
...‌گذشته ارائه می‌شود. پرداخت منظم بدهی‌های مالیاتی از عوامل مؤثر در افزایش امتیاز اعتباری است و تأخیر یا بدهی مالیاتی می‌تواند موجب کاهش آن شود.‌...
DocumentName: IndividualCreditReport | Title: توضیحات بخش‌های مختلف گزارش اعتباری اشخاص حقیقی | SectionTitle: خلاصه قراردادها | Content: در این قسمت، خلاصه‌ای از قراردادهای  فرد (وام و دیگر تسهیلات) در نقش‌های مختلف (متقاضی اصلی، شریک یا ضامن) نمایش داده می‌شود. برای هر نقش، اطلاعات زیر ارائه می‌گردد:
نوع قرارداد
نام اعتباردهنده (بانک یا مؤسسه مالی)
تعداد قراردادهای جاری و خاتمه‌یافته
مبلغ کل قراردادها
مبلغ سررسید‌نشده (بدهی‌های آتی)
مبلغ سررسیدشده پرداخت‌نشده | Type: مقاله | Version: 1 | Author(s): محمدی | Heading: 9.1 | Keywords: [قرارداد مالی، تسهیلات، ضامن، متقاضی، بانک، مؤسسه مالی، بدهی، قرارداد جاری، خلاصه بدهی] | Summary: در این قسمت، خلاصه‌ای از قراردادهای مالی و اعتباری فرد در نقش‌های مختلف (متقاضی اصلی، شریک یا ضامن) نمایش داده می‌شود. برای هر نقش، اطلاعات زیر ارائه می‌گردد:
نوع قرارداد
نام اعتباردهنده (بانک یا مؤسسه مالی)
تعداد قراردادهای جاری و خاتمه‌یافته
مبلغ کل قراردادها
مبلغ سررسید‌نشده (بدهی‌های آتی)
مبلغ سررسیدشده پرداخت‌نشده
```
**Word stats:** query↔gold Jaccard=0.072 (shared 5: ['بدهیمو', 'بعدش', 'پرداخت', 'کار', 'کردم']); query↔winner Jaccard=0.014 (shared 1: ['پرداخت']); gold_len=754 winner_len=1108
**Gold content words absent from winner:** ['استعلام', 'اصلاح', 'اقساط', 'الوصول', 'بازپرداخت', 'باشد', 'بدهیمو', 'بدون', 'بعدش', 'بعدی', 'بمانید', 'بندی', 'بیش', 'تاخیر', 'تسهیلاتی', 'توسط', 'حداکثر', 'خارج', 'دریافت', 'دسته', 'ذکر', 'روز', 'روزرسانی', 'زمان', 'سابقه']

## [7] IndividualCRMQuestions#353 (type A)
**QUERY:** من وام نىارم C بهم دادین چرا؟

**GOLD** [qa_pair]  (ranks bm25=None dense=None merged=None final=None)
```
...‌کشد تا امتیاز شما پس از پرداخت اقساط سررسید شده از ۲۵۰ خارج شود. کلیدواژه‌ها: ماهانه، اطلاعات تسهیلات دسته‌بندی: اصلاح و به‌روزرسانی اطلاعات مدل: حقیقی‌...
سوال: من وام نىارم C بهم دادین چرا؟
پاسخ کوتاه: شرکت اعتبارسنجی ایران با طراحی یک مدل اعتبارسنجی جدید، به تمامی افراد بالای ۱۸ سال که حداقل یک حساب بانکی دارند، رتبه اعتباری اختصاص می‌دهد؛ فارغ از اینکه سابقه تسهیلاتی داشته باشند یا خیر.
پاسخ کامل: شرکت اعتبارسنجی ایران با طراحی یک مدل اعتبارسنجی جدید، به تمامی افراد بالای ۱۸ سال که حداقل یک حساب بانکی دارند، رتبه اعتباری اختصاص می‌دهد. برای افرادی که سابقه دریافت تسهیلات ندارند، رتبه اعتباری بر اساس عواملی مانند سوابق مالیاتی، صدک درآمدی، چک برگشتی و ضمانت محاسبه می‌شود. رتبه این افراد در بازه C قرار می‌گیرد و تعیین رتبه دقیق، یعنی C2، C1 یا C3، به وضعیت عوامل مؤثر در امتیاز بستگی دارد. توجه داشته باشید که مدل امتیازدهی افراد فاقد سابقه تسهیلاتی با مدل مورد استفاده برای افراد دارای سابقه تسهیلاتی متفاوت است.
کلیدواژه‌ها: رتبه C، بدون سابقه، مدل جایگزین حقیقی، صدک و مالیات و چک
دسته‌بندی: امتیاز و رتبه اعتباری
مدل: حقیقی
```
**ACTUAL RETRIEVED WINNER** (stage=final_top5)
```
...‌بهبود دهید تا امتیازتان افزایش پیدا کند. کلیدواژه‌ها: [رتبه اعتباری C، اعطای وام، تصمیم بانک، ریسک، محدودیت وام] دسته‌بندی: تسهیلات، وام‌گیری و ضمانت مدل: حقیقی‌...
سوال: شما با چه معیاری تصمیم می گیرید که چه کسی صلاحیت دریافت وام را دارد؟
پاسخ کوتاه: ما تصمیم نمی‌گیریم؛ فقط گزارش ارائه می‌دهیم. بانک تصمیم می‌گیرد.
پاسخ کامل: شرکت اعتبارسنجی ایران هیچ‌گونه تصمیمی درباره صلاحیت یا عدم صلاحیت مشتری برای دریافت وام نمی‌گیرد. وظیفه ما تنها ارائه گزارش و امتیاز اعتباری بر اساس داده‌های واقعی رفتار اعتباری افراد است. بانک‌ها در تصمیم‌گیری خود علاوه بر امتیاز اعتباری، موارد زیر را نیز بررسی می‌کنند: 1. نوع تسهیلات 2. میزان درآمد و توان بازپرداخت 3. تضامین ارائه‌شده 4. سوابق بانکی 5. سیاست‌های داخلی بانک بنابراین تصمیم نهایی کاملاً در اختیار بانک است.
کلیدواژه‌ها: [معیار صلاحیت وام، تصمیم بانک، امتیاز اعتباری، شرایط تسهیلات، اعطای وام، سوابق]
دسته‌بندی: تسهیلات، وام‌گیری و ضمانت
مدل: حقیقی
```
**Word stats:** query↔gold Jaccard=0.045 (shared 4: ['بهم', 'دادین', 'نىارم', 'وام']); query↔winner Jaccard=0.013 (shared 1: ['وام']); gold_len=1043 winner_len=898
**Gold content words absent from winner:** ['C1', 'C2', 'C3', 'اختصاص', 'استفاده', 'اصلاح', 'اطلاعات', 'افرادی', 'اقساط', 'امتیازدهی', 'اینکه', 'بازه', 'باشند', 'باشید', 'بالای', 'بدون', 'برگشتی', 'بستگی', 'بهم', 'تسهیلاتی', 'تعیین', 'تمامی', 'توجه', 'جایگزین', 'جدید']

## [8] IndividualCRMQuestions#361 (type A)
**QUERY:** آیا چک ها و تسهیلات در بازه زمانی 9 اسفند 1404 تا 9 خرداد 1405 در امتیاز و رتبه اعتباری موثرند؟

**GOLD** [qa_pair]  (ranks bm25=None dense=None merged=None final=None)
```
...‌انتقال، امتیاز هیچ‌ شخص دیگری، جز صادرکننده اصلی متأثر نمی‌شود. کلیدواژه‌ها: انتقال چک، تأثیر فقط بر صادرکننده، عدم تأثیر بر گیرنده دسته‌بندی: چک مدل: حقیقی‌...
سوال: آیا چک ها و تسهیلات در بازه زمانی 9 اسفند 1404 تا 9 خرداد 1405 در امتیاز و رتبه اعتباری موثرند؟
پاسخ کوتاه: در بازه ۹ اسفند ۱۴۰۴ تا ۹ خرداد ۱۴۰۵، با توجه به نظر بانک مرکزی، سوابق چک برگشتی و تسهیلات معوق مشمول شرایط، در محاسبه رتبه و امتیاز اعتباری لحاظ نشده است.
پاسخ کامل: براساس ابلاغیه هیأت عالی بانک مرکزی، کلیه تسهیلات و تعهدات معوق مربوط به بازه زمانی ۹ اسفند ۱۴۰۴ تا ۹ خرداد ۱۴۰۵، در صورتی که مبلغ کل تسهیلات ۷۰۰ میلیون تومان و مانده تسهیلات ۵۰۰ میلیون تومان باشد، در سابقه اعتباری و گزارش‌های اعتبارسنجی به‌عنوان نمره منفی محاسبه نمی‌شوند. همچنین، کلیه چک‌های برگشتی مربوط به این بازه زمانی، مشروط به رفع سوءاثر، امتیاز و رتبه اعتباری را تحت تاثیر قرار نمی‌دهند.
کلیدواژه‌ها: بخشنامه بانک مرکزی، عدم احتساب تسهیلات معوق، عدم احتساب چک برگشتی
دسته‌بندی: اختلال و جنگ و بخشنامه
مدل: حقیقی
```
**ACTUAL RETRIEVED WINNER** (stage=final_top5)
```
...‌ایفای تعهدات شما در تسهیلات، چک و مالیات است. کلیدواژه‌ها: تغییر شغل، محل سکونت، بدون اثر، رتبه اعتباری دسته‌بندی: عوامل موثر بر امتیاز مدل: حقیقی‌...
سوال: آیا اشخاص حقوقی نیز اعتبارسنجی می شوند؟
پاسخ کوتاه: بله، شرکت‌ها دارای امتیاز اعتبارسنجی تسهیلات هستند.
پاسخ کامل: بله. در ایران، اشخاص حقوقی (شرکت‌ها و سازمان‌ها) نیز دارای گزارش و امتیاز اعتبارسنجی تسهیلات هستند و امتیاز آن ها بر اساس عملکرد تسهیلاتی  و اعتباری آن‌ها محاسبه می شود. البته در نسخه فعلی امتیاز اعتبارسنجی کسب و کارها، تنها کسب و کارهایی دارای رتبه و امتیاز اعتباری هستند که سابقه کافی در بازپرداخت اقساط تسهیلات در گذشته داشته باشند.
کلیدواژه‌ها: شرکت‌ها، امتیاز اعتباری، عملکرد مالی، تسهیلات
دسته‌بندی: مفاهیم پایه اعتبارسنجی
مدل: حقیقی
```
**Word stats:** query↔gold Jaccard=0.143 (shared 12: ['1404', '1405', 'اسفند', 'اعتباری', 'امتیاز', 'بازه', 'تسهیلات', 'خرداد', 'رتبه', 'زمانی', 'موثرند', 'چک']); query↔winner Jaccard=0.076 (shared 5: ['اعتباری', 'امتیاز', 'تسهیلات', 'رتبه', 'چک']); gold_len=966 winner_len=715
**Gold content words absent from winner:** ['1404', '1405', 'ابلاغیه', 'احتساب', 'اختلال', 'اسفند', 'اصلی', 'انتقال', 'بازه', 'باشد', 'بانک', 'بخشنامه', 'براساس', 'برگشتی', 'تأثیر', 'تاثیر', 'تحت', 'توجه', 'تومان', 'جز', 'جنگ', 'خرداد', 'دهند', 'دیگری', 'رفع']

## [9] IndividualCRMQuestions#365 (type A)
**QUERY:** من یه چک داشتم برا آخر تیر، که چون بانکم صادرات بود پاس نشد. این امتیازمو کم میکنه؟

**GOLD** [qa_pair]  (ranks bm25=None dense=None merged=None final=None)
```
...‌شوند، مشمول این قاعده خواهند بود. کلیدواژه‌ها: اختلال سیستمی بانک‌ها چهار بانک مشمول مهلت تسویه ۱۵ شهریور دسته‌بندی: اختلال و جنگ و بخشنامه مدل: حقیقی‌...
سوال: من یه چک داشتم برا آخر تیر، که چون بانکم صادرات بود پاس نشد. این امتیازمو کم میکنه؟
پاسخ کوتاه: با توجه به نظر بانک مرکزی، سوابق چک و تسهیلات معوق برای بانک‌های ملی، صادرات، تجارت و توسعه صادرات، در بازه ۲۳ خرداد ۱۴۰۵ تا ۱۵ شهریور ۱۴۰۵، در محاسبه رتبه و امتیاز اعتباری لحاظ نمی‌شود.
پاسخ کامل: براساس ابلاغیه هیأت عالی بانک مرکزی، کلیه تسهیلات و تعهدات سررسیدشده پرداخت‌نشده مربوط به بازه زمانی اختلال سیستمی بانک‌های ملی ایران، صادرات ایران، تجارت و توسعه صادرات ایران از تاریخ ۲۳ خرداد ۱۴۰۵، مشروط بر اینکه حداکثر تا ۱۵ شهریور ۱۴۰۵ تسویه شوند، در سابقه اعتباری و گزارش‌های اعتبارسنجی به‌عنوان نمره منفی محاسبه نمی‌شوند. همچنین، چک‌های برگشتی مربوط به این چهار بانک در دوره اختلال، مشروط بر اینکه حداکثر تا ۱۵ شهریور ۱۴۰۵ رفع سوءاثر شوند، مشمول این قاعده خواهند بود.
کلیدواژه‌ها: اختلال سیستمی بانک‌ها چهار بانک مشمول مهلت تسویه ۱۵ شهریور
دسته‌بندی: اختلال و جنگ و بخشنامه
مدل: حقیقی
```
**ACTUAL RETRIEVED WINNER** (stage=final_top5)
```
...‌کامل: بله تاثیرگذارند و مانند چکهای برگشتی مربوط به حسابهای انفرادی امتیاز را کاهش میدهند. کلیدواژه‌ها: چند امضا کننده، چند صادرکننده، حساب مشترک مدل: چک‌...
سوال: تفاوت رتبه و امتیاز در چک چیست؟
پاسخ کوتاه: در واقع هر دو یک مفهوم را نشان میدهند و هر رتبه نشان دهنده بازه ای از امتیاز است مثلا امتیاز 85 تا 100 نشان دهنده  رتبه A است.
پاسخ کامل: امتیاز چک عددی بین 1 تا 100 است و رتبه چک از E3 تا A1 می باشد. در واقع هر دو یک مفهوم را نشان میدهند و هر رتبه نشان دهنده بازه ای از امتیاز است مثلا امتیاز 85 تا 100 نشان دهنده  رتبه A است.
کلیدواژه‌ها: عدد امتیاز، امتیاز چک، رتبه چک
مدل: چک
```
**Word stats:** query↔gold Jaccard=0.167 (shared 14: ['آخر', 'امتیازمو', 'بانکم', 'برا', 'تیر', 'داشتم', 'صادرات', 'میکنه', 'نشد', 'پاس', 'چون', 'چک', 'کم', 'یه']); query↔winner Jaccard=0.018 (shared 1: ['چک']); gold_len=1049 winner_len=591
**Gold content words absent from winner:** ['آخر', 'ابلاغیه', 'اختلال', 'اعتبارسنجی', 'اعتباری', 'امتیازمو', 'ایران', 'اینکه', 'بانک', 'بانکم', 'بخشنامه', 'برا', 'براساس', 'بندی', 'تاریخ', 'تجارت', 'تسهیلات', 'تسویه', 'تعهدات', 'توجه', 'توسعه', 'تیر', 'جنگ', 'حداکثر', 'حقیقی']

## [10] IndividualCRMQuestions#366 (type A)
**QUERY:** من بیس و سه تومن قسط ملیمو از مرداد ندادم. این امتیازمو کم میکنه؟

**GOLD** [qa_pair]  (ranks bm25=84 dense=None merged=None final=None)
```
...‌شوند، مشمول این قاعده خواهند بود. کلیدواژه‌ها: اختلال سیستمی بانک‌ها چهار بانک مشمول مهلت تسویه ۱۵ شهریور دسته‌بندی: اختلال و جنگ و بخشنامه مدل: حقیقی‌...
سوال: من بیس و سه تومن قسط ملیمو از مرداد ندادم. این امتیازمو کم میکنه؟
پاسخ کوتاه: با توجه به نظر بانک مرکزی، سوابق چک و تسهیلات معوق برای بانک‌های ملی، صادرات، تجارت و توسعه صادرات، در بازه ۲۳ خرداد ۱۴۰۵ تا ۱۵ شهریور ۱۴۰۵، در محاسبه رتبه و امتیاز اعتباری لحاظ نمی‌شود.
پاسخ کامل: براساس ابلاغیه هیأت عالی بانک مرکزی، کلیه تسهیلات و تعهدات سررسیدشده پرداخت‌نشده مربوط به بازه زمانی اختلال سیستمی بانک‌های ملی ایران، صادرات ایران، تجارت و توسعه صادرات ایران از تاریخ ۲۳ خرداد ۱۴۰۵، مشروط بر اینکه حداکثر تا ۱۵ شهریور ۱۴۰۵ تسویه شوند، در سابقه اعتباری و گزارش‌های اعتبارسنجی به‌عنوان نمره منفی محاسبه نمی‌شوند. همچنین، چک‌های برگشتی مربوط به این چهار بانک در دوره اختلال، مشروط بر اینکه حداکثر تا ۱۵ شهریور ۱۴۰۵ رفع سوءاثر شوند، مشمول این قاعده خواهند بود.
کلیدواژه‌ها: اختلال سیستمی بانک‌ها چهار بانک مشمول مهلت تسویه ۱۵ شهریور
دسته‌بندی: اختلال و جنگ و بخشنامه
مدل: حقیقی
```
**ACTUAL RETRIEVED WINNER** (stage=final_top5)
```
...‌positive: فرد در 3 ماه گذشته در بازپرداخت اقساط خود بسیار خوش حساب بوده است. | code positive: IPADTB6 | Fico: 4.404266517 | group: DC‌...
feature: NMonthWithNoDelinq1ContrL3M_Main_AllCon | bins: Missing | WoE: 0.01848870576409212 | sum_IV: 0.05902939923488087 | Gini: 11.39958914064636 | bad_rate: 0.1919614529645111 | coefficient: -0.7851763629426377 | variable_point: -0.5445297535894476 | feature_score: 3.372149182511469 | source: تسهیلات | Fico: 29.40637701 | group: DC
```
**Word stats:** query↔gold Jaccard=0.122 (shared 10: ['امتیازمو', 'بیس', 'تومن', 'سه', 'قسط', 'مرداد', 'ملیمو', 'میکنه', 'ندادم', 'کم']); query↔winner Jaccard=0.000 (shared 0: []); gold_len=1031 winner_len=478
**Gold content words absent from winner:** ['ابلاغیه', 'اختلال', 'اعتبارسنجی', 'اعتباری', 'امتیاز', 'امتیازمو', 'ایران', 'اینکه', 'بازه', 'بانک', 'بخشنامه', 'براساس', 'برگشتی', 'بندی', 'بیس', 'تاریخ', 'تجارت', 'تسویه', 'تعهدات', 'توجه', 'توسعه', 'تومن', 'جنگ', 'حداکثر', 'حقیقی']

## [11] IndividualCRMQuestions#375 (type A)
**QUERY:** اگه چک پاس شده داشته باشم تو امتیازم موثره؟

**GOLD** [qa_pair]  (ranks bm25=None dense=None merged=None final=None)
```
...‌اطلاع‌رسانی را دریافت نخواهید کرد. کلیدواژه‌ها: پیامک اطلاع‌رسانی استعلام، استعلام بانکی، شماره متناظر با کد ملی، تأیید شماره دسته‌بندی: حریم خصوصی و دسترسی مدل: حقیقی‌...
سوال: اگه چک پاس شده داشته باشم تو امتیازم موثره؟
پاسخ کوتاه: در حال حاضر خیر.
پاسخ کامل: در نسخه فعلی مدل اعتبارسنجی، چک‌های پاس‌شده تأثیری بر امتیاز اعتباری شما ندارند و صرفاً چک‌های برگشتی در محاسبه امتیاز مؤثرند؛ با این حال، تمام چک‌های صادره در گزارش اعتباری شما ثبت می‌شوند.
دسته‌بندی: چک
مدل: حقیقی
```
**ACTUAL RETRIEVED WINNER** (stage=final_top5)
```
...‌در سامانه چک های برگشتی بانک مرکزی موجب کاهش امتیاز اعتباری می‌شوند. کلیدواژه‌ها: چک برگشتی، بانک مرکزی، امتیاز اعتباری، سامانه صیاد دسته‌بندی: چک مدل: حقوقی‌...
سوال: آیا داشتن چک‌های پاس‌شده زیاد، تأثیر مثبتی روی امتیاز اعتباری کسب و کار دارد؟
پاسخ کوتاه: بله.
پاسخ کامل: تعداد چک های نقد شده بر امتیاز کسب و کار موثر است.
کلیدواژه‌ها: چک پاس‌شده، تاثیر اندک
دسته‌بندی: چک
مدل: حقوقی
```
**Word stats:** query↔gold Jaccard=0.137 (shared 7: ['امتیازم', 'اگه', 'باشم', 'داشته', 'موثره', 'پاس', 'چک']); query↔winner Jaccard=0.051 (shared 2: ['پاس', 'چک']); gold_len=481 winner_len=389
**Gold content words absent from winner:** ['استعلام', 'اطلاع', 'اعتبارسنجی', 'امتیازم', 'اگه', 'باشم', 'بانکی', 'تأثیری', 'تأیید', 'تمام', 'ثبت', 'حاضر', 'حال', 'حریم', 'حقیقی', 'خصوصی', 'خیر', 'داشته', 'دریافت', 'دسترسی', 'رسانی', 'شماره', 'صادره', 'صرفا', 'فعلی']

## [12] IndividualCRMQuestions#376 (type A)
**QUERY:** چکم پاس شد کی امتیازدار میشم؟

**GOLD** [qa_pair]  (ranks bm25=99 dense=None merged=None final=None)
```
...‌ندارند و صرفاً چک‌های برگشتی در محاسبه امتیاز مؤثرند؛ با این حال، تمام چک‌های صادره در گزارش اعتباری شما ثبت می‌شوند. دسته‌بندی: چک مدل: حقیقی‌...
سوال: چکم پاس شد کی امتیازدار میشم؟
دسته‌بندی: چک
مدل: حقیقی
```
**ACTUAL RETRIEVED WINNER** (stage=final_top5)
```
...‌کوتاه: بله. پاسخ کامل: تعداد چک های نقد شده بر امتیاز کسب و کار موثر است. کلیدواژه‌ها: چک پاس‌شده، تاثیر اندک دسته‌بندی: چک مدل: حقوقی‌...
سوال: آیا چک‌هایی که به دلیل کسری مبلغ اندک برگشت خورده‌اند، به همان اندازه چک‌های برگشت خورده دیگر اثر منفی دارند؟
پاسخ کوتاه: بله، چک برگشتی رفع سواثر نشده فارغ از مبلغ آن امتیاز اعتباری کسب و کار را به ۲۵۰ و رتبه اعتباری را به E3 کاهش می‌دهد.
پاسخ کامل: بله، چک برگشتی رفع سواثر نشده فارغ از مبلغ آن، امتیاز اعتباری کسب و کار را به پایین ترین امتیاز (۲۵۰) کاهش می‌دهد. البته پس از رفع سو اثر امتیاز کسب و کار افزایش می یابد ولی سوابق چک برگشتی (مبلغ چک برگشت‌خورده، مدت زمان گذشته از برگشت خوردن چک، تعداد چک‌های برگشتی و فاصله زمانی برگشت چک و رفع سو اثر آن) تا ۵ سال در گزارش اعتباری شما موجود است و در امتیاز شما تاثیر می گذارد.
کلیدواژه‌ها: رفع سوءاثر، چک، بهبود امتیاز، برگشت چک
دسته‌بندی: چک
مدل: حقوقی
```
**Word stats:** query↔gold Jaccard=0.208 (shared 5: ['امتیازدار', 'میشم', 'پاس', 'چکم', 'کی']); query↔winner Jaccard=0.015 (shared 1: ['پاس']); gold_len=211 winner_len=854
**Gold content words absent from winner:** ['امتیازدار', 'تمام', 'ثبت', 'حال', 'حقیقی', 'شوند', 'صادره', 'صرفا', 'مؤثرند', 'محاسبه', 'میشم', 'ندارند', 'چکم', 'کی']
